### PR TITLE
build with shared, also handle extra dependencies on NCEPLIBS-bufr and mystery libraries

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #169 
Part of #160

### CODE REVIEW

**Review by AlexanderRichert-NOAA — COMMENTED** [review]
I get the following error when compiling with `-DBUILD_SHARED_LIBS=ON`; both `test_summary` and `test_w3tagb` fail to build:
```
../src/libw3emc_d.so: undefined reference to `getarg_'
../src/libw3emc_d.so: undefined reference to `w3fi33_'
../src/libw3emc_d.so: undefined reference to `iargc_'
../src/libw3emc_d.so: undefined reference to `int2ch_'
../src/libw3emc_d.so: undefined reference to `consol_'
collect2: error: ld returned 1 exit status
```

**Comment by AlexanderRichert-NOAA** [comment]
The issue is fixed with `-DBUILD_WITH_EXTRA_DEPS=OFF`... I guess that's expected as a result of these mysterious external dependencies?

**Comment by aerorahul** [comment]
```
if(@BUILD_WITH_BUFR@)
    find_dependency(bufr)
endif()
```
should be added to [PackageConfig.cmake.in](https://github.com/NOAA-EMC/NCEPLIBS-w3emc/tree/ejh_shared_1_31/cmake/PackageConfig.cmake.in)

**Comment by edwardhartnett** [comment]
OK, try again, I've fixed some things.

You can't build with shared libraries unless you set -DBUILD_WITH_EXTRA_DEPS=OFF. I've added a check in the main cmake file to check that.

**Review by AlexanderRichert-NOAA — APPROVED** [review]

**Pull request merged**
