### PR TITLE
Add Spack-based CI workflow

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
This PR adds a Spack-based CI workflow.

squash-n-merge

### CODE REVIEW

**Comment by edwardhartnett** [comment]
Is this ready to merge?

**Comment by AlexanderRichert-NOAA** [comment]
Not quite, still waiting on a spack recipe update upstream- I'm happy to circle back to it after you merge the items you're currently working on.

**Comment by edwardhartnett** [comment]
@AlexanderRichert-NOAA if you can get this done I will do a release, so that we have working shared libs. Need that to get shared libs working in other NCEPLIBS that depend on w3emc.

**Comment by AlexanderRichert-NOAA** [comment]
@edwardhartnett the bufr recipe update may be a while yet, so I took out the tests with bufr if you want to go ahead and merge as it is, then I can add it later once that's ready.

**Review by edwardhartnett — APPROVED** [review]

**Pull request merged**
