### PR TITLE
Deprecate unused code

### LINKED ISSUE #227: Deprecate unused subroutines
w3emc contains a number of subroutines that don't appear to be used in operations. Most of them seem to provide fairly arcane functionality (i.e., for old Crays and IBMs). Specifically, all of the subroutines in the following files are not used in operational model executables, executables built by spack-stack (incl. grib_util), and decoders: aea.f, q9ie32.f, w3ai00.f, w3ai01.f, w3ai08.f, w3ai18.f, w3ai38.f, w3ai40.f, w3ai41.f, w3aq15.f, w3ctzdat.f, w3fa01.f, w3fa03v.f, w3fa04.f, w3fa06.f, w3fa11.f, w3fa12.f, w3fa13.f, w3fb00.f, w3fb01.f, w3fb02.f, w3fb03.f, w3fb04.f, w3fc02.f, w3fc08.f, w3fi02.f, w3fi03.f, w3fi18.f, w3fi19.f, w3fi20.f, w3fi32.f, w3fi47.f, w3fi48.f, w3fi61.f, w3fi64.f, w3fi65.f, w3fi66.f, w3fi67.f, w3fi70.f, w3fi78.f, w3fi85.f, w3fi88.f, w3fi92.f, w3fm07.f, w3fm08.f, w3fp04.f, w3fp05.f, w3fp06.f, w3fp10.f, w3fp12.f, w3fp13.f, w3ft00.f, w3ft02.f, w3ft03.f, w3ft05.f, w3ft05v.f, w3ft06.f, w3ft06v.f, w3ft07.f, w3ft08.f, w3ft09.f, w3ft10.f, w3ft11.f, w3ft12.f, w3ft201.f, w3ft202.f, w3ft203.f, w3ft204.f, w3ft205.f, w3ft206.f, w3ft207.f, w3ft208.f, w3ft209.f, w3ft210.f, w3ft211.f, w3ft212.f, w3ft213.f, w3ft214.f, w3ft21.f, w3ft32.f, w3ft33.f, w3ft38.f, w3ft39.f, w3ft40.f, w3ft41.f, w3ft43v.f, w3log.f, w3nogds.f, w3ymdh4.f, xdopen.f, iw3unp29.f, w3miscan.f, w3unpk77.f

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
This PR adds a CMake option that disables a bunch of unused subroutines by default.

Fixes #227

### CODE REVIEW

**Review by edwardhartnett — APPROVED** [review]
OK, I like the decisiveness! ;-)

So in spack-stack these will also be off by default?

**Review by Hang-Lei-NOAA — APPROVED** [review]

**Comment by AlexanderRichert-NOAA** [comment]
@edwardhartnett correct. With spack-stack it's pretty easy to make quick updates (such as to enable a variant), so I'd rather switch them off as a starting point, then developers can let us know if we took away something they needed.

**Comment by edwardhartnett** [comment]
So we should probably do a release?

**Comment by AlexanderRichert-NOAA** [comment]
Yep, I intend to do that shortly

**Pull request merged**
