### PR TITLE
Doxygen for 39 files (Part of #77)

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
Doxygen for:
- modified: src/w3ft201.f
- modified: src/w3ft202.f
- modified: src/w3ft203.f
- modified: src/w3ft204.f
- modified: src/w3ft205.f
- modified: src/w3ft206.f
- modified: src/w3ft207.f
- modified: src/w3ft208.f
- modified: src/w3ft209.f
- modified: src/w3ft21.f
- modified: src/w3ft210.f
- modified: src/w3ft211.f
- modified: src/w3ft212.f
- modified: src/w3ft213.f
- modified: src/w3ft214.f
- modified: src/w3ft26.f
- modified: src/w3ft32.f
- modified: src/w3ft33.f
- modified: src/w3ft38.f
- modified: src/w3ft39.f
- modified: src/w3ft40.f
- modified: src/w3ft41.f
- modified: src/w3ft43v.f
- modified: src/w3kind.f
- modified: src/w3locdat.f
- modified: src/w3miscan.f
- modified: src/w3movdat.f
- modified: src/w3nogds.f
- modified: src/w3pradat.f
- modified: src/w3reddat.f
- modified: src/w3tagb.f
- modified: src/w3trnarg.f
- modified: src/w3unpk77.f
- modified: src/w3utcdat.f
- modified: src/w3valdat.f
- modified: src/w3ymdh4.f
- modified: src/xdopen.f
- modified: src/xmovex.f
- modified: src/xstore.f

Part of #77

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
I decided to crank through the rest of W3EMC files. So now all files should be Doxygenated. There's some final edits I need to make to w3unpk77.f still. Those will wait until Monday with a new PR.

**Comment by BrianCurtis-NOAA** [comment]
Pinging @edwardhartnett  and @Hang-Lei-NOAA this may take a bit of time.

**Comment by Hang-Lei-NOAA** [comment]
Usually, if the code is only one edit, We don't need to add the program history log.

**Comment by BrianCurtis-NOAA** [comment]
> Usually, if the code is only one edit, We don't need to add the program history log.

OK. I was wondering that too but kept it for consistency between all the other Doxygen. Should I remove the one-only PHL entries?

**Comment by Hang-Lei-NOAA** [comment]
Well, you can keep it as well. There may need a unified standard later.

**Review by Hang-Lei-NOAA — APPROVED** [review]

**Pull request merged**
