### PR TITLE
Update tests to use CMake

### PR DESCRIPTION
**Pull request by kgerheiser**
This takes Boi's #63 and converts it to use CMake.

Now you just run `make test`

@BoiVuong-NOAA can you elaborate on what this test tests exactly?

Need to distribute the data somehow. I have it set to symlink `tests/data` to `build/tests/data`.

### CODE REVIEW

**Review by BoiVuong-NOAA — APPROVED** [review]

**Review by BoiVuong-NOAA — APPROVED** [review]

**Review by BoiVuong-NOAA — COMMENTED** [review]
What Do I need to do for this request ?

**Comment by kgerheiser** [comment]
If you could give me a brief overview of what this test is doing that would be helpful.

Otherwise, the test data needs to be uploaded somewhere and the CMake needs to download it, and then it will be ready.

**Comment by BoiVuong-NOAA** [comment]
Kyle,

This test program reads an grib file. Then, It generates a grib index. 
After that, it reads the grib index file to display the content of grib 
file.

So, this test will test a number of routines in w3emc.  See example:

testw3emc gfs.t00z.pgrb2.0p25.f012_grib1 gfs.t00z.pgrb2.0p25.f012_grib1.idx

where input file is grib file (gfs.t00z.pgrb2.0p25.f012_grib1)

the output file is (gfs.t00z.pgrb2.0p25.f012_grib1.idx)

It displays on screen number of grib files from the 
(gfs.t00z.pgrb2.0p25.f012_grib1.idx) file.

INVENTORY FOR FILE = gfs.t00z.pgrb2.0p25.f012_grib1.idx

  PRODUCT DEFINITION SECTION (PDS) OF EACH RECORD.
  SEE NMC OFFICE NOTE 388 ON GRIB (WMO CODE FM 92-IX EXT.)

  N0001 00001C02 0760C180 0B640096 15010E00 0001000C 0A000000 15000001
                 150 ISBL  TMP    12  HRS AFTER 00Z  14 JAN 2021 1168104
  N0002 00001C02 0760C180 076400C8 15010E00 0001000C 0A000000 15000002
                 200 ISBL  HGT    12  HRS AFTER 00Z  14 JAN 2021 2076564
  N0003 00001C02 0760C180 346400C8 15010E00 0001000C 0A000000 15000001
                 200 ISBL  R H    12  HRS AFTER 00Z  14 JAN 2021 1297884
  N0004 00001C02 0760C180 21640096 15010E00 0001000C 0A000000 15000002
                 150 ISBL  U GRD  12  HRS AFTER 00Z  14 JAN 2021 1817004
  N0005 00001C02 0760C180 22640096 15010E00 0001000C 0A000000 15000002
                 150 ISBL  V GRD  12  HRS AFTER 00Z  14 JAN 2021 1817004

  END OF INVENTORY FOR FILE = gfs.t00z.pgrb2.0p25.f012_grib1.idx,     5 
GRIB RECORDS.
  FILE NUMBER  1, IT HAS         8176560 BYTES IN FILE.

Testing NCEPLIBS-w3emc: SUCCESS !

NOTE:
I do not have an FTP account to place these test files.  Do you have one 
?  Can you up load them to FTP site ?  They are:

gfs.t00z.pgrb2.0p25.f012_grib1

gfs.t00z.pgrb2.0p25.f012_grib1.idx

Thanks,

Boi

**Comment by kgerheiser** [comment]
@edwardhartnett this is ready except for test data. How can we get it uploaded? Or is it worth storing this data in the repo? It's pretty small.

**Comment by edwardhartnett** [comment]
The best would be to create a tarball and send it to Kate to put on the FTP site. Even if the data files are small now, probably we will need to add more...

**Comment by BoiVuong-NOAA** [comment]
Can you request for nceplibs team to have an account of FTP server ? This way, we can update any files without asking Kate to upload files for us.

**Comment by edwardhartnett** [comment]
Yes, I will ask.

**Comment by edwardhartnett** [comment]
OK, we will bump this to the next release...

**Comment by edwardhartnett** [comment]
What's the deal with this PR? Are we going to proceed with it? Or should we close it and start again?

**Pull request closed without merging**
