### PR TITLE
GCC 10 flags, compiler check, and settable flags

### PR DESCRIPTION
**Pull request by kgerheiser**

### CODE REVIEW

**Review by climbfuji — APPROVED** [review]

**Comment by climbfuji** [comment]
Just noting that the automatic tests failed.

**Review by aerorahul — APPROVED** [review]

**Comment by aerorahul** [comment]
> Just noting that the automatic tests failed.

yeah, just saw that too.  Why the heck in the netCDF not building in the environment. weird ...

**Comment by aerorahul** [comment]
> > Just noting that the automatic tests failed.
> 
> yeah, just saw that too. Why the heck in the netCDF not building in the environment. weird ...

```
Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4-gnutls-dev_7.68.0-1ubuntu2.1_amd64.deb  404  Not Found [IP: 52.168.50.79 80]
```

**Comment by kgerheiser** [comment]
Adding `apt-get update` seems to have fixed it.

**Pull request merged**
